### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by jglick** [jenkinsci/docker-inbound-agents#31]
Do not use the term _JNLP_. Do you mean _inbound agent_?

**Comment by timja** [comment]
Done, ci.jenkins.io and trusted.ci.jenkins.io updated as well

**Comment by jglick** [comment]
> group … into one repository

That would make sense.

> something like « docker-inbound-collection » or « docker-agent-tools »

Sure. No particular opinion as I have little knowledge of this repo or who relies on it.

**Comment by lemeurherveCB** [comment]
> I want to propose a jep to group « docker-agent », « docker-inbound-agent » (singular) and « docker-ssh-agent » into one repository « docker-agent » as they depend on each other (or should).

Related:
- https://github.com/jenkinsci/docker-agent/issues/749

> renaming here something like « docker-inbound-collection » or « docker-agent-tools » as they are aimed at providing « tools » ?

+1, I would propose "docker-inbound-examples".

> (I would personnally vote to stop maintenance of this assets and archive it given the compatibility matrix that we have to keep. Providing a nice documentation showing a Dockerfile example - eventually a generator- would make more sense)

+100

**Comment by dduportal** [comment]
Hi: we are closing this issue as this repository and associated Docker image are now archived as per #51 .
