### ISSUE TITLE
Push on commit

### ISSUE THREAD

**Issue by pablogrs** [jenkinsci/docker-inbound-agents#36]
### What feature do you want to see added?

Hi, it seems that after changes in the repo images are not being pushed to Docker hub? 
At least I cannot see the changes done to Ruby image recently.
https://hub.docker.com/r/jenkins/jnlp-agent-ruby/tags

Would it be possible to automate this part?

**Comment by dduportal** [comment]
Update: the job in charge of deploying these images was removed 14-15 months ago in the private controller in charge of deploying images.

The job's been added back to sustain the deployment: it might need a few fixes on the pipeline before succeeding.

**Comment by dduportal** [comment]
Hi @pablogrs , the problem is now solved: can you confirm?

**Comment by pablogrs** [comment]
Hi, the image is there, thank you.
